<?php

$words = array(
	1 => array(
		'Az MVC szemléletmód szerint kell',
		'Tárolt eljárások alkalmazásával szükséges',
		'A funkcionális specifikáció alapján indokolt',
		'A megtervezett architektúra szerint érdemes',
		'Maximális hatékonysággal kell',
		'A felhasználói szokásokat figyelembe véve ajánlott',
		'Kiemelt prioritással kell',
		'Figyelembe véve a határidőket muszáj',
		'Az agilitás jegyében elengedhetetlen',
		'A vezető fejlesztő szerint szükségszerű',
		'A szoftvertermék fejlesztési folyamatok kialakítása alapján javallott',
		'A konkrét krízishelyzetek elkerülése végett fontos',
		'A bottleneck-ek felkutatásával kezdve célszerű',
		'A projekt státusz riport szerint megéri',
		'A mobilstratégia miatt elvárt',
		'A kódolási konvenciók követése miatt célravezető',
		'A retrospektíven megbeszéltek miatt elkerülhetetlen',
		'A backend és a frontend terhelés egyensúlyának érdekében létfontosságú',
		'Titkosított kapcsolaton keresztül javasolt',
		'A rendszer által kínált hozzáférés-kezelés miatt szükséges',
		'A felhasználói felületre helyezve a hangsúlyt indokolt',
		'A speciális karakterek numerikus hivatkozássá való kódolásához javasolt',
		'Az offline működés érdekében tanácsos',
		'A verziókövetés miatt ajánlott',
		'A nagyméretű, robosztus üzleti alkalmazások miatt kell',
		'A nagy hálózatokat kiszolgáló szerverek miatt elengedhetetlen',
		'A túl sok I/O művelet miatt elengedhetetlen',
		'A sémafordító segítségével lehet',
		'A webszolgáltatások vermével lehetséges',
		'A terheléselosztás és a rendszer méretezhetősége miatt szükséges',
		'A rendszerezett metadatokkal kell',
		'Az adminisztrációs felülethez szükséges',
		'A http requestek számának csökkentése érdekében nélkülözhetetlen',
		'A megtervezett, kapacitásilag a lehetőségekhez mérten feltöltött projekt megvalósítása érdekében szükséges',
		'A projekt indító dokumentum szerint kell',
		'A tesztjegyzőkönyvek alapján indokolt',
		'A felhő által nyújtott szolgáltatásokkal lehet',
		'A fejlesztői és üzemeltetői teamek hatékony együttműködése érdekében fontos',
		'Felhő-alapú fájlmegosztó rendszer használatával kell',
		'Támogatottsági problémák miatt tanácsos',
		'A gördülékeny, felhasználóbarát működés miatt kívánatos',
		'Automatizált feladatvégrehajtó-eszközzel érdemes',
		'A kódminőség miatt fontos',
		'Programtervezési minták használatával javasolt',
		'A UI kit alapján kell',
		'A routing érdekében kell',
		'A vízeséses modell terminológiája szerint ajánlott',
		'Az elfogadási kritériumok teljesülése érdekében tanácsos',
		'A backlog groomingok alkalmával véglegesített sztorik miatt kell',
		'LAMP környezetben érdemes',
		'A technical dept kiküszöbölése érdekében szükséges',
		'A wireframe-ek alapján kell',
		'Az előzetesen kiválasztott keretrendszert használva érdemes'

	),
	2 => array(
		'A/B tesztelni',
		'beégetni',
		'elkészíteni',
		'felmérni',
		'kibővíteni',
		'kielemezni',
		'kódolni',
		'letesztelni',
		'megtervezni',
		'minify-olni',
		'optimalizálni',
		'lefordítani',
		'refaktorálni',
		'supportálni',
		'újraírni',
		'újratervezni',
		'debuggolni',
		'lefejleszteni',
		'leprogramozni',
		'hash-elni',
		'kommentelni',
		'indexelni',
		'beágyazni',
		'installálni',
		'telepíteni',
		'cache-elni',
		'szerializálni',
		'konfigurálni',
		'konvertálni',
		'loggolni',
		'naplózni',
		'meghívni',
		'implementálni',
		'származtatni',
		'örköltetni',
		'buildelni',
		'lokalizálni',
		'kasztolni'
	),
	3 => array(
		'a rendelkezésre álló',
		'a költséges',
		'a WEB 2.0 normák szerinti',
		'a decentralizált',
		'az objektum-orientált',
		'a reszponzív',
		'a dinamikus',
		'a platformfüggetlen',
		'a globális',
		'a releváns',
		'a statikus',
		'az alapértelmezett',
		'a rekurzív',
		'az alkalmazásspecifikus',
		'a base64 kódolású',
		'a séma szerinti',
		'a rugalmas',
		'a paraméterezett',
		'a jól struktúrált',
		'a kívánt',
		'a definiált',
		'a kiterjesztett',
		'a testreszabott',
		'a megfelelő',
		'a távoli',
		'a szekvenciális',
		'a kompatibilis',
		'az opcionális',
		'a böngészőspecifikus',
		'a kliensoldali',
		'a szerveroldali',
		'a végtelen',
		'a bináris',
		'a böngészőfüggetlen',
		'a protokollnak megfelelő',
		'a kapcsolat nélkül is elérhető',
		'az elosztott',
		'a független',
		'a natív',
		'a szintaktikailag megfelelő',
		'a valós idejű',
		'az eseményvezérelt',
		'az újrafelhasználható',
		'a flexibilis',
		'a példányosított',
		'az időzített',
		'a kritikus',
		'a hátultesztelős'
	),
	4 => array(
		'kódbázist',
		'scripteket',
		'betöltődési időt',
		'futási időt',
		'memóriahasználatot',
		'felületeket',
		'üzleti célokat',
		'felhasználói célokat',
		'technikai korlátokat',
		'szubrutinokat',
		'bugokat',
		'API-t',
		'tesztrendszereket',
		'URL-t',
		'dokumentációt',
		'osztályokat',
		'változókat',
		'funkcionalitást',
		'adatbázist',
		'relációs adatmodellt',
		'webes alkalmazást',
		'aktív szerveroldalakat',
		'többdimenziós tömböket',
		'konstansokat',
		'adatbázistáblákat',
		'attribútumokat',
		'függvényeket',
		'lekérdezéseket',
		'munkameneteket',
		'konstruktort',
		'ciklusokat',
		'fájlokat',
		'visszatérési értéket',
		'interfészt',
		'utasításokat',
		'cookie-kat',
		'reguláris kifejezéseket',
		'appot',
		'fájlinformációkat',
		'kompenzációs tranzakciókat',
		'bemeneti és kimeneti értékeket',
		'erőforrás-leíró keretrendszert',
		'láncolt listákat',
		'frameworköt',
		'nyelvi fájlokat',
		'auto layoutot',
		'storyboardot'
	),
);
?>